Repository ergebnis/composer-normalize, pull requests merged in 2019-12, with the labels that each got.

#247 Fix: Use assertStringContainsString() instead of assertContains()
  test/Integration/Command/NormalizeCommandTest.php
Labels: bug

#246 Enhancement: Synchronize project tooling configuration with ergebnis/php-library-template
  .dependabot/config.yml
  .gitattributes
  .github/CONTRIBUTING.md
  .github/settings.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/stale.yml
  Makefile
  composer-require-checker.json
  phpstan-baseline.neon
  phpstan.neon
Labels: enhancement

#249 Fix: Remove protection for master branch
  .github/settings.yml
Labels: bug

#250 Fix: Remove branch alias
  composer.json
  composer.lock
Labels: bug

#251 Fix: Set master as default branch
  .github/settings.yml
Labels: bug

#256 Enhancement: Use ergebnis/test-util instead of localheinz/test-util
  composer.json
  composer.lock
  test/Integration/Command/NormalizeCommandTest.php
Labels: enhancement

#257 Enhancement: Use ergebnis/phpstan-rules instead of localheinz/phpstan-rules
  composer.json
  composer.lock
  phpstan.neon
Labels: enhancement

#258 Enhancement: Synchronize with ergebnis/php-library-template
  .github/settings.yml
  .github/stale.yml
  .github/workflows/continuous-integration.yml
  Makefile
  README.md
  composer.json
  composer.lock
  phpstan.neon
  test/AutoReview/phpunit.xml
  test/Unit/phpunit.xml
Labels: enhancement

#248 Enhancement: Run builds on PHP 7.4
  .github/settings.yml
  .github/workflows/continuous-integration.yml
Labels: enhancement

#260 Fix: References in CHANGELOG.md
  CHANGELOG.md
Labels: bug

#261 Enhancement: Use ergebnis/composer-json-normalizer instead of localheinz/composer-json-normalizer
  CHANGELOG.md
  composer.json
  composer.lock
  src/Command/NormalizeCommand.php
  src/NormalizePlugin.php
  test/Integration/Command/NormalizeCommandTest.php
Labels: enhancement

#262 Fix: Remove default values of $formatter abd $differ parameters
  CHANGELOG.md
  phpstan-baseline.neon
  src/Command/NormalizeCommand.php
  src/NormalizePlugin.php
  test/Integration/Command/NormalizeCommandTest.php
Labels: bug

#267 Enhancement: Synchronize with ergebnis/php-library-template
  .dependabot/config.yml
  .github/CODEOWNERS
  .github/CODE_OF_CONDUCT.md
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/continuous-integration.yml
  Makefile
Labels: enhancement

#268 Fix: Rename namespace after move to @ergebnis
  .github/workflows/continuous-integration.yml
  .php_cs
  CHANGELOG.md
  README.md
  composer.json
  composer.lock
  phpstan-baseline.neon
  src/Command/NormalizeCommand.php
  src/Command/SchemaUriResolver.php
  src/NormalizePlugin.php
  test/Integration/Command/NormalizeCommandTest.php
  test/Util/CommandInvocation.php
  test/Util/Directory.php
  test/Util/File.php
  test/Util/Scenario.php
  test/Util/State.php
Labels: bug

#269 Fix: Reference
  README.md
Labels: bug

#270 Fix: Mark classes as internal
  CHANGELOG.md
  src/Command/NormalizeCommand.php
  src/Command/SchemaUriResolver.php
Labels: bug

#272 Fix: Remove useless DocBlocks
  CHANGELOG.md
  src/Command/NormalizeCommand.php
Labels: bug

#273 Fix: Remove SchemaUriResolver and check in schema.json instead
  CHANGELOG.md
  resource/schema.json
  src/Command/SchemaUriResolver.php
  src/NormalizePlugin.php
  test/Integration/Command/NormalizeCommandTest.php
Labels: bug

#274 Fix: Reference
  CHANGELOG.md
Labels: bug

#279 Enhancement: Synchronize with ergebnis/php-library-template
  .dependabot/config.yml
  .github/settings.yml
  .github/workflows/continuous-integration.yml
Labels: enhancement

#280 Fix: Bring back support for PHP 7.1
  .github/settings.yml
  .github/workflows/continuous-integration.yml
  CHANGELOG.md
  Makefile
  composer.json
  composer.lock
Labels: bug

#281 Enhancement: Update phpstan/phpstan and friends
  composer.json
  composer.lock
  phpstan.neon
  src/Command/NormalizeCommand.php
  src/Exception/Exception.php
  src/Exception/ShouldNotHappen.php
  test/Integration/Command/NormalizeCommandTest.php
  test/Unit/Exception/ShouldNotHappenTest.php
  test/Util/Scenario.php
Labels: dependency

#282 Enhancement: Synchronize with ergebnis/php-library-template
  .dependabot/config.yml
  .github/settings.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/stale.yml
  Makefile
Labels: enhancement

#284 Update README.md links
  README.md
Labels: bug

#285 Enhancement: Require phpstan/phpstan-phpunit
  composer.json
  composer.lock
  test/Unit/Exception/ShouldNotHappenTest.php
Labels: enhancement

#286 Fix: Run 'make coding-standards'
  test/Unit/Exception/ShouldNotHappenTest.php
Labels: bug

#275 Compare local and online schema.json in CI
  .github/workflows/schema.yml
Labels: enhancement

#287 Enhancement: Add badge for schema
  .github/workflows/schema.yml
  README.md
Labels: enhancement

#288 Enhancement: Commit updated schema back to master
  .github/workflows/schema.yml
Labels: enhancement

#289 Fix: Use personal access token
  .github/workflows/schema.yml
Labels: bug

#290 Fix: Run schema workflow every hour
  .github/workflows/schema.yml
Labels: bug

#291 Enhancement: Show diff
  .github/workflows/schema.yml
Labels: enhancement

#292 Enhancement: Compile, sign, and upload composer-normalize.phar on tag
  .dependabot/config.yml
  .gitattributes
  .github/workflows/continuous-deployment.yml
  .github/workflows/continuous-integration.yml
  .gitignore
  CHANGELOG.md
  Makefile
  README.md
  phar/box.json
  phar/box.phar
  phar/composer-normalize.php
  phar/composer.json
  phar/composer.lock
  phar/keys.asc.gpg
Labels: enhancement

#293 Fix: Build composer-normalize.phar in Continuous Integration workflow
  .github/settings.yml
  .github/workflows/continuous-integration.yml
Labels: bug

#294 Enhancement: Simplify Phar compilation
  .dependabot/config.yml
  .gitattributes
  .github/workflows/continuous-deployment.yml
  .github/workflows/continuous-integration.yml
  Makefile
  box.json
  phar/composer-normalize.php
  phar/composer.json
  phar/composer.lock
Labels: enhancement

#295 Fix: Receive key
  .github/workflows/continuous-deployment.yml
Labels: bug

#296 Enhancement: Add note about Phar and installation with PHIVE
  README.md
Labels: enhancement

#297 Fix: Actually run 'composer validate'
  CHANGELOG.md
  src/Command/NormalizeCommand.php
  test/Integration/Command/NormalizeCommandTest.php
Labels: bug

#298 Enhancement: Simplify update of locker
  src/Command/NormalizeCommand.php
Labels: enhancement

#299 Fix: Check for schema updates only once a day
  .github/workflows/schema.yml
Labels: bug

#300 Enhancement: Show version of ergebnis/composer-normalize
  .github/workflows/continuous-integration.yml
  box.json
  composer-require-checker.json
  phar/composer-normalize.php
  phpstan.neon
  src/Application.php
  test/Unit/ApplicationTest.php
Labels: enhancement

#301 Fix: Actually allow passing argument and options to command
  .github/workflows/continuous-integration.yml
  CHANGELOG.md
  Makefile
  phar/composer-normalize.php
Labels: bug
