Repository ergebnis/composer-normalize, pull requests merged in 2020-07, with the labels that each got.

#479 Fix: Update composer/composer
  .github/workflows/integrate.yaml
  .github/workflows/release.yaml
  Makefile
  composer.json
  composer.lock
Labels: bug, dependency

#480 Fix: Lock to stable version of composer/composer
  composer.lock
Labels: bug, merge

#482 Fix: Use appropriate data provider
  test/Integration/Command/NormalizeCommandTest.php
Labels: bug, merge

#481 Fix: Ignore platform requirements when updating lock file
  CHANGELOG.md
  src/Command/NormalizeCommand.php
  test/Fixture/json/valid/lock/not-present/json/already-normalized/composer.json
  test/Fixture/json/valid/lock/not-present/json/not-yet-normalized/composer.json
  test/Fixture/json/valid/lock/present/lock/fresh-before/json/already-normalized/composer.json
  test/Fixture/json/valid/lock/present/lock/fresh-before/json/already-normalized/composer.lock
  test/Fixture/json/valid/lock/present/lock/fresh-before/json/not-yet-normalized/lock/fresh-after/composer.json
  test/Fixture/json/valid/lock/present/lock/fresh-before/json/not-yet-normalized/lock/fresh-after/composer.lock
  test/Fixture/json/valid/lock/present/lock/fresh-before/json/not-yet-normalized/lock/not-fresh-after/composer.json
  test/Fixture/json/valid/lock/present/lock/fresh-before/json/not-yet-normalized/lock/not-fresh-after/composer.lock
  test/Fixture/json/valid/lock/present/lock/not-fresh-before/composer.json
  test/Fixture/json/valid/lock/present/lock/not-fresh-before/composer.lock
Labels: bug, merge

#465 Add support for PHP 8.0
  .github/settings.yml
  .github/workflows/integrate.yaml
  CHANGELOG.md
  composer.json
  composer.lock
Labels: enhancement

#488 Fix: Update CHANGELOG.md
  CHANGELOG.md
Labels: bug, merge

#498 Fix: Use caret operator
  composer.json
  composer.lock
Labels: bug, merge
