Repository ergebnis/composer-normalize, pull requests merged in 2020-03, with the labels that each got.

#375 Enhancement: Require composer/composer:^1.10.0
  .github/workflows/continuous-deployment.yml
  .github/workflows/continuous-integration.yml
  composer.json
  composer.lock
  test/Fixture/json/valid/lock/present/lock/fresh-before/json/already-normalized/composer.lock
  test/Fixture/json/valid/lock/present/lock/fresh-before/json/not-yet-normalized/lock/fresh-after/composer.lock
  test/Fixture/json/valid/lock/present/lock/fresh-before/json/not-yet-normalized/lock/not-fresh-after/composer.lock
Labels: dependency

#376 Enhancement: Synchronize with ergebnis/php-library-template
  .dependabot/config.yaml
  .editorconfig
  .github/CONTRIBUTING.md
  .github/settings.yml
  .github/workflows/integrate.yaml
  .github/workflows/prune.yaml
  .github/workflows/release.yaml
  .github/workflows/renew.yaml
  .github/workflows/update.yaml
  .php_cs
  .yamllint.yaml
  CHANGELOG.md
  Makefile
  README.md
  phpstan.neon
  psalm-baseline.xml
  psalm.xml
  test/Integration/phpunit.xml
  test/Unit/phpunit.xml
Labels: enhancement

#377 Fix: Use same version of composer/composer
  Makefile
Labels: bug

#379 Fix: Update composer/composer
  .github/workflows/integrate.yaml
  .github/workflows/release.yaml
  CHANGELOG.md
  Makefile
  composer.json
  composer.lock
Labels: bug

#380 Fix: Reference
  .github/workflows/release.yaml
  CHANGELOG.md
Labels: bug

#385 Fix README.md links
  README.md
Labels: bug
