Repository ergebnis/composer-normalize, pull requests merged in 2021-11, with the labels that each got.

#803 Updated `README.md` - optimize console command's
  .github/CONTRIBUTING.md
  README.md
Labels: enhancement

#807 Fix: Drop support for `composer/composer:^1.0.0`
  .github/settings.yml
  .github/workflows/integrate.yaml
  CHANGELOG.md
  composer.json
  composer.lock
Labels: bug, dependency

#808 Enhancement: Run tests on PHP 8.1
  .github/settings.yml
  .github/workflows/integrate.yaml
Labels: enhancement

#809 Fix: Wrapping
  src/Command/NormalizeCommand.php
  src/NormalizePlugin.php
Labels: bug

#810 Fix: Remove `phpstan/phpstan`
  .gitattributes
  .github/CONTRIBUTING.md
  .github/workflows/integrate.yaml
  Makefile
  composer.json
  composer.lock
  phpstan-baseline.neon
  phpstan.neon
Labels: bug, dependency

#811 Fix: Do not cache cache directory for `vimeo/psalm`
  .github/workflows/integrate.yaml
Labels: bug

#812 Enhancement: Install `humbug/box` with `phive`
  .github/workflows/integrate.yaml
  .github/workflows/release.yaml
  .phive/box
  .phive/phars.xml
  Makefile
Labels: enhancement, dependency

#813 Enhancement: Update `humbug/box`
  .phive/box
  .phive/phars.xml
Labels: enhancement, dependency

#804 Enhancement: Update `composer/composer`
  .github/workflows/integrate.yaml
  .github/workflows/release.yaml
  CHANGELOG.md
  Makefile
  composer-require-checker.json
  composer.json
  composer.lock
  src/Command/NormalizeCommand.php
Labels: enhancement, dependency

#814 Fix: Name
  .github/workflows/integrate.yaml
  .github/workflows/release.yaml
  .github/workflows/renew.yaml
  .github/workflows/update.yaml
Labels: bug
